### ISSUE TITLE
No build for FreeBSD amd64 available

### ISSUE THREAD

**Issue by kdambekalns** [sandstorm/synco#13]
😞

**Comment by skurfuerst** [comment]
will provide one @kdambekalns In the next days  :) :)

**Comment by skurfuerst** [comment]
Fixed in Version 1.1.0 - see https://github.com/sandstorm/synco/commit/e00233d35c552ea8ed395ef4c4498c443054116a and https://github.com/sandstorm/synco/commit/3f98a4112c0e1220f05cefede456208fb3477995
